# Generated by Django 5.1.1 on 2024-09-14 11:22

import markdownx.models
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="iconlink",
            options={"verbose_name": "Icon Link", "verbose_name_plural": "Icon Links"},
        ),
        migrations.AlterModelOptions(
            name="textlink",
            options={"verbose_name": "Text Link", "verbose_name_plural": "Text Links"},
        ),
        migrations.AlterField(
            model_name="project",
            name="description",
            field=markdownx.models.MarkdownxField(),
        ),
        migrations.AlterField(
            model_name="work",
            name="description",
            field=markdownx.models.MarkdownxField(),
        ),
    ]
