# Generated by Django 5.1.1 on 2024-09-15 18:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0002_alter_iconlink_options_alter_textlink_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="personalinfo",
            name="links",
            field=models.ManyToManyField(blank=True, to="cms.iconlink"),
        ),
    ]
