# Generated by Django 5.1.1 on 2024-09-09 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_personalinfo_delete_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('iconify_logo', models.CharField(max_length=100)),
                ('link', models.URLField()),
            ],
            options={
                'verbose_name_plural': 'Technologies',
            },
        ),
        migrations.AlterModelOptions(
            name='personalinfo',
            options={'verbose_name': 'Personal Information'},
        ),
    ]
